version : "3.3"
services : 
  connector-management :
    build : .
    image : worker-01:5000/connector-management
    networks: 
      - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports : 
      - 5001:5001
    volumes :
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  default:
    external:
#      name: apicekmitl_network
      name: ticketing_default_test
