version : "3.3"
services : 
  connectors :
    build : .
    image : worker-01:5000/connector-management
    networks: 
      - default
    extra_hosts :
      - "mongo:172.16.0.6"
    restart: always
    ports : 
      - 5001:5001
  
networks:
  default:
    external:
#      name: apicekmitl_network
      name: ticketing_default_test
