version : "3.4"
services : 
  connector-management :
    build : 
      context: .
      network: host
    image : worker1:5000/connector-management
    networks: 
      - default
    extra_hosts :
      - "mongo:192.168.2.199"
    restart: always
    ports : 
      - 5001:5001
    volumes :
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  default:
    external:
#      name: apicekmitl_network
      name: ticketing_default
